# Generated by Django 2.2.10 on 2021-03-25 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ClientSide', '0002_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
